{
 "title": "GGX Chain Grafana Dashboard",
 "description": " <= [ Build by ART3MIS.CLOUD with LOVE ❤️ ] => Complete Grafana Dashboard for GGXChain. Applicable to all Subrtrate base with minimum configuration changes.",
 "tags": [
  "GGXChain",
  "Substrate"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "♻️ [ ALL CONNECTED INSTANCES OVERVIEW ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chain Flow In Blocks",
     "type": "timeseries",
     "description": "Provide basic overview on blocks flow for ALL connected instances.\n\nIf required can add specific job as: substrate_block_height{job=\"my_job\"}",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
     "targets": [
      { "expr": "ggxnode_substrate_block_height", "legendFormat": "{{ alias }} - {{ status }}" }
     ]
    },
    {
     "title": "Nodes missions",
     "type": "stat",
     "description": "Our instance mission. Display if node is validator or just passive observe.",
     "gridPos": { "h": 10, "w": 5, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(rate(ggxnode_substrate_finality_grandpa_precommits_total[$__rate_interval]) + rate(ggxnode_substrate_finality_grandpa_prevotes_total[$__rate_interval])) / 2",
       "legendFormat": "[ {{ instance }} ] ==>"
      }
     ]
    },
    {
     "title": "Grandpa Finality Round",
     "type": "timeseries",
     "description": "Overview on grandpa roudns progression for ALL connected instances.\n\nIf required can add specific job as: substrate_finality_grandpa_round{job=\"my_job\"}",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
     "targets": [
      {
       "expr": "ggxnode_substrate_finality_grandpa_round",
       "legendFormat": "{{ alias }} - {{ job }}"
      }
     ]
    },
    {
     "title": "Block Flow [ all ]",
     "type": "timeseries",
     "description": "Chain flow stability overview, can provide some ideas on general lag in consensus.\n\nIf required can add specific job as: \nincrease(substrate_block_height{job=\"my_job\"}[5m])",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(ggxnode_substrate_block_height[200s]) / 100",
       "legendFormat": "{{ alias }} - {{ status }}"
      }
     ]
    },
    {
     "title": "Grandpa Round Flow Control [ 1m ]",
     "type": "timeseries",
     "description": "Grandpa rounds progression overview.\n\nAdd job if required as:\nincrease(substrate_finality_grandpa_round{job=\"my_job\"}[1m])",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(ggxnode_substrate_finality_grandpa_round[150s]) / 100",
       "legendFormat": "finality_grandpa_round - {{ alias }}"
      }
     ]
    }
   ]
  },
  {
   "title": "👀  Basic Overview - [ $job ] - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peers count:",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_peers_count{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "Peers count:"
      }
     ]
    },
    {
     "title": "Block [ $instance ]",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ggxnode_substrate_block_height{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "! NODE MISSION !",
     "type": "stat",
     "description": "Our instance mission. Display if node is validator or just passive observe.",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expression": "$A + $B / 2", "type": "math" }
     ]
    },
    {
     "title": "build_info [ $instance ]",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ggxnode_substrate_build_info{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "Grandpa Round  [ $instance ]",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ggxnode_substrate_finality_grandpa_round{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "finality_grandpa_round:"
      }
     ]
    },
    {
     "title": "Chain Flow Control [ $instance ]",
     "type": "timeseries",
     "description": "Calculated [1m] / 30 = ~1",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(ggxnode_substrate_block_height{instance=\"$instance\",job=\"$job\"}[1m]) / 30",
       "legendFormat": "{{ alias }} - {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "⚙️  Consensus [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "block_verification_time [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_block_verification_time_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) / rate(ggxnode_substrate_block_verification_time_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Time:"
      }
     ]
    },
    {
     "title": "avg ~ block_verification_and_import_time  [$__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_block_verification_and_import_time_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) / rate(ggxnode_substrate_block_verification_and_import_time_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Time:"
      }
     ]
    },
    {
     "title": "database_cache_bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_database_cache_bytes{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "database_cache_bytes:"
      }
     ]
    },
    {
     "title": "finality_grandpa_communication_gossip_validator_messages [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_finality_grandpa_communication_gossip_validator_messages{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{action}} <==> {{ message }}"
      }
     ]
    },
    {
     "title": "Grandpa finality tota [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_finality_grandpa_precommits_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "finality_grandpa_precommits_tota:"
      },
      {
       "expr": "rate(ggxnode_substrate_finality_grandpa_prevotes_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "finality_grandpa_prevotes_total:"
      }
     ]
    },
    {
     "title": "finality_grandpa_round",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_finality_grandpa_round{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "finality_grandpa_round:"
      }
     ]
    },
    {
     "title": "finality_grandpa_until_imported_waiting_messages_number",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_finality_grandpa_until_imported_waiting_messages_number{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "finality_grandpa_until_imported_waiting_messages_number:"
      }
     ]
    },
    {
     "title": "issued_light_requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_issued_light_requests{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "issued_light_requests:"
      }
     ]
    },
    {
     "title": "import_queue_processed_total [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_import_queue_processed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "import_queue_processed_total:"
      }
     ]
    },
    {
     "title": "gossip_registered_messages [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_network_gossip_registered_messages_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "gossip_registered_messages:"
      }
     ]
    },
    {
     "title": "gossip_expired_messages [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_network_gossip_expired_messages_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "gossip_expired_messages:"
      }
     ]
    },
    {
     "title": "justification_import_time [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_justification_import_time_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) / rate(ggxnode_substrate_justification_import_time_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "justification_import_time:"
      }
     ]
    },
    {
     "title": "Node Roles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "substrate_node_roles{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "Role:"
      }
     ]
    },
    {
     "title": "process start time",
     "type": "stat",
     "description": "Number of seconds between the UNIX epoch and the moment the process started.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ggxnode_substrate_process_start_time_seconds{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "number_leaves"
      }
     ]
    },
    {
     "title": "number_leaves",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_number_leaves{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "number_leaves"
      }
     ]
    }
   ]
  },
  {
   "title": "⚙️  RPC  [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "rpc_calls_time [ long calls tracker ]",
     "type": "bargauge",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_rpc_calls_time_sum{instance=\"$instance\",job=\"$job\"}[5m]) / rate(ggxnode_substrate_rpc_calls_time_count{instance=\"$instance\",job=\"$job\"}[5m])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc_calls_time rate => [ avg per $__range ] <=",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_rpc_calls_time_sum{instance=\"$instance\",job=\"$job\"}[$__range]) / rate(ggxnode_substrate_rpc_calls_time_count{instance=\"$instance\",job=\"$job\"}[$__range])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc_calls_finished",
     "type": "timeseries",
     "gridPos": { "h": 24, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_rpc_calls_finished{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc_calls_started",
     "type": "timeseries",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_rpc_calls_started{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc_calls_time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_rpc_calls_time_sum{instance=\"$instance\",job=\"$job\"}[5m]) / rate(ggxnode_substrate_rpc_calls_time_count{instance=\"$instance\",job=\"$job\"}[5m])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "ready_transactions_number",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "substrate_ready_transactions_number{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "ready_transactions_number"
      }
     ]
    },
    {
     "title": "rpc_requests_finished",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_rpc_requests_finished{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "rpc_requests_finished - [ {{ protocol }} ]"
      },
      {
       "expr": "rate(substrate_rpc_requests_started{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "rpc_requests_started - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc session status [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_rpc_sessions_closed{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Session Closed"
      },
      {
       "expr": "rate(substrate_rpc_sessions_opened{job=\"$job\",instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Session Open:"
      }
     ]
    }
   ]
  },
  {
   "title": "⚙️  P2P  [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "connections_closed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_connections_closed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ reason }}: [ {{ direction }} ]"
      }
     ]
    },
    {
     "title": "connections_open",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_connections_opened_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "incoming_connections_handshake_errors [$__rate_interval]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_incoming_connections_handshake_errors_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "libp2p_distinct_peers_connections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_distinct_peers_connections_closed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Close:"
      },
      {
       "expr": "rate(substrate_sub_libp2p_distinct_peers_connections_opened_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Open:"
      }
     ]
    },
    {
     "title": "libp2p_incoming_connections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_incoming_connections_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Incoming P2P connections rate:"
      }
     ]
    },
    {
     "title": "libp2p_is_major_syncing",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_is_major_syncing{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "libp2p_is_major_syncing"
      }
     ]
    },
    {
     "title": "kademlia_random_queries [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_kademlia_random_queries_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "kademlia_random_queries"
      }
     ]
    },
    {
     "title": "kademlia_records_count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_kademlia_records_count{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "kademlia_records_count"
      }
     ]
    },
    {
     "title": "kademlia_records_sizes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_kademlia_records_sizes_total{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "kademlia_records_sizes"
      }
     ]
    },
    {
     "title": "libp2p_kbuckets_num_nodes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_kbuckets_num_nodes{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "[ {{ lower_ilog2_bucket_bound }} ]"
      }
     ]
    },
    {
     "title": "libp2p_notifications_streams [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_notifications_streams_closed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Closed - {{ protocol }}"
      },
      {
       "expr": "rate(substrate_sub_libp2p_notifications_streams_opened_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Opened - {{ protocol }}"
      }
     ]
    },
    {
     "title": "libp2p_notifications_sizes [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_notifications_sizes_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) / rate(ggxnode_substrate_sub_libp2p_notifications_sizes_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ direction }} - {{ protocol }}"
      }
     ]
    },
    {
     "title": "libp2p_listeners_errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_listeners_errors_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "libp2p_listeners_errors"
      }
     ]
    },
    {
     "title": "libp2p_listeners_local_addresses",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_listeners_local_addresses{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "libp2p_listeners_local_addresses"
      }
     ]
    },
    {
     "title": "libp2p_out_events_events rate",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_out_events_events_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ event_name }} - {{ name }}"
      }
     ]
    },
    {
     "title": "libp2p_out_events_notifications_sizes [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_out_events_notifications_sizes{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ event_name }} - {{ name }}"
      }
     ]
    },
    {
     "title": "libp2p_out_events_num_channels",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_out_events_num_channels{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "{{ event_name }} - {{ name }}"
      }
     ]
    },
    {
     "title": "libp2p_pending_connections",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_pending_connections{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "libp2p_pending_connections"
      }
     ]
    },
    {
     "title": "Peers count:",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_peers_count{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "Peers count:"
      }
     ]
    },
    {
     "title": "libp2p_requests_out_failure",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_requests_out_failure_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ protocol }} - {{ reason }}"
      }
     ]
    },
    {
     "title": "peerset_num_discovered",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_sub_libp2p_peerset_num_discovered{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "peerset_num_discovered"
      }
     ]
    },
    {
     "title": "pending_connections_errors [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_pending_connections_errors_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "libp2p_requests_out_success [ $__rate_interval ]",
     "type": "timeseries",
     "description": "Histogram processed as:\n( Sum / Count [$__rate_interval] )",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_libp2p_requests_out_success_total_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) / rate(ggxnode_substrate_sub_libp2p_requests_out_success_total_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ protocol }}"
      }
     ]
    }
   ]
  },
  {
   "title": " 🏹  TX Pool  [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "txpool_block_transactions_pruned [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_txpool_block_transactions_pruned{instance=\"$instance\",job=\"$job\"}[5m])",
       "legendFormat": "Time:"
      }
     ]
    },
    {
     "title": "txpool_block_transactions_pruned [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_txpool_block_transactions_pruned{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "txpool_block_transactions_pruned"
      }
     ]
    },
    {
     "title": "transactions_resubmitted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_txpool_block_transactions_resubmitted{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "transactions_resubmitted"
      }
     ]
    },
    {
     "title": "txpool_validations_finished [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_txpool_validations_finished{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) > 0",
       "legendFormat": "txpool_validations_finished"
      }
     ]
    },
    {
     "title": "txpool_validations_invalid",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_txpool_validations_invalid{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "txpool_validations_invalid"
      }
     ]
    },
    {
     "title": "txpool_validations_scheduled / txpool_submitted_transactions [ $__rate_interval ]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_sub_txpool_validations_scheduled{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "txpool_validations_scheduled"
      },
      {
       "expr": "rate(substrate_sub_txpool_submitted_transactions{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "txpool_submitted_transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "🔋 Storage  [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "state_cache_bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ggxnode_substrate_state_cache_bytes{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "state_cache_bytes:"
      }
     ]
    },
    {
     "title": "storage_notification_subscribers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_storage_notification_subscribers{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ action }}:"
      }
     ]
    }
   ]
  },
  {
   "title": "⚠️  => Alerts Example <=",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chain Flow => [ Alert Example ] <=",
     "type": "timeseries",
     "description": "Given the inherent dynamism of network behaviors, it is reasonable to anticipate fluctuating values over time. Consequently, it is advisable to align temporal parameters with the approximate intervals of block processing. The calibration of alerting thresholds demands a deliberate manual intervention to achieve optimal sensitivity. The visual representation provided here serves as a generic illustrative instance, showcasing the potential instantiation of alerts.\n\nIn the event of specificity being requisite, it is plausible to incorporate a distinct job, exemplified as: substrate_block_height{job=\"my_job\"}",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 403 },
     "targets": [
      {
       "expr": "delta(ggxnode_substrate_block_height[60s]) / 30 ",
       "legendFormat": "{{ alias }} - {{ status }}"
      }
     ]
    },
    {
     "title": "Grandpa Rounds Flow => [ Alert Example ] <=",
     "type": "timeseries",
     "description": "Given the inherent dynamism of network behaviors, it is reasonable to anticipate fluctuating values over time. Consequently, it is advisable to align temporal parameters with the approximate intervals of grandpa rounds length. The calibration of alerting thresholds demands a deliberate manual intervention to achieve optimal sensitivity. The visual representation provided here serves as a generic illustrative instance, showcasing the potential instantiation of alerts.\n\nIn the event of specificity being requisite, it is plausible to incorporate a distinct job, exemplified as: substrate_finality_grandpa_round{job=\"my_job\"}",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 403 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(ggxnode_substrate_finality_grandpa_round[152s]) / 100",
       "legendFormat": "finality_grandpa_round - {{ alias }}"
      }
     ]
    },
    {
     "title": "Validation [ Alert ]",
     "type": "timeseries",
     "description": "If value fall below dashed line, we are not validator anymore. This should be considered as maximum severity level as much as fatal.\n\nAlerts doesn't support variables, target required instance manualy. Example: instance=\"my_ec2_instance\",job=\"my_validator\"",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 403 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ggxnode_substrate_finality_grandpa_precommits_total{instance=\"$instance\",job=\"$job\"}[15s])",
       "legendFormat": "finality_grandpa_precommits_tota:"
      },
      {
       "expr": "rate(ggxnode_substrate_finality_grandpa_prevotes_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "finality_grandpa_prevotes_total:"
      }
     ]
    }
   ]
  }
 ]
}