{
 "title": "Golden Gate Custom [ A3MC ]",
 "description": "ART3MIS.CLOUD DEBUG BOARD FOR SUBSTRATE BASE",
 "tags": [
  "substrate",
  "GoldenGate"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(substrate_block_height[5m])",
     "legendFormat": "{{ instance }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Grandpa Round",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(substrate_finality_grandpa_round[1m])",
     "legendFormat": "finality_grandpa_round - {{ instance }}"
    }
   ]
  },
  { "title": "Basic Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Peers count:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Peers count:"
    }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Grandpa Round",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_round{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "finality_grandpa_round:"
    }
   ]
  },
  {
   "title": "build_info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_build_info{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Grandpa Finality Round",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_round",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Chain Flow Control",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(substrate_block_height{instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "{{ alias }} - {{ status }}"
    }
   ]
  },
  { "title": "Unsorted", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "block_verification_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(substrate_block_verification_time_sum{instance=\"$instance\",job=\"$job\"}[5m]) / rate(substrate_block_verification_time_count{instance=\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "Time:"
    }
   ]
  },
  {
   "title": "block_verification_and_import_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(substrate_block_verification_and_import_time_sum{instance=\"$instance\",job=\"$job\"}[5m]) / rate(substrate_block_verification_and_import_time_count{instance=\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "Time:"
    }
   ]
  },
  {
   "title": "database_cache_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "substrate_database_cache_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "database_cache_bytes:"
    }
   ]
  },
  {
   "title": "finality_grandpa_communication_gossip_validator_messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ message }}"
    }
   ]
  },
  {
   "title": "finality_grandpa_precommits_tota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_precommits_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "finality_grandpa_precommits_tota:"
    }
   ]
  },
  {
   "title": "finality_grandpa_prevotes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_prevotes_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "finality_grandpa_prevotes_total:"
    }
   ]
  },
  {
   "title": "finality_grandpa_round",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_round{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "finality_grandpa_round:"
    }
   ]
  },
  {
   "title": "finality_grandpa_until_imported_waiting_messages_number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_until_imported_waiting_messages_number{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "finality_grandpa_until_imported_waiting_messages_number:"
    }
   ]
  },
  {
   "title": "issued_light_requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_issued_light_requests{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "issued_light_requests:"
    }
   ]
  },
  {
   "title": "import_queue_processed_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_import_queue_processed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "import_queue_processed_total:"
    }
   ]
  },
  {
   "title": "gossip_registered_messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_network_gossip_registered_messages_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "gossip_registered_messages:"
    }
   ]
  },
  {
   "title": "gossip_expired_messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_network_gossip_expired_messages_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "gossip_expired_messages:"
    }
   ]
  },
  {
   "title": "justification_import_time rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_justification_import_time_sum{instance=\"$instance\",job=\"$job\"}[5m]) / rate(substrate_justification_import_time_count{instance=\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "justification_import_time:"
    }
   ]
  },
  {
   "title": "Node Role",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_node_roles{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Role:"
    }
   ]
  },
  {
   "title": "process start time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "substrate_process_start_time_seconds{instance=\"$instance\",job=\"$job\"} / 12960000 / 60",
     "legendFormat": "number_leaves"
    }
   ]
  },
  {
   "title": "number_leaves",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_number_leaves{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "number_leaves"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "rpc_calls_finished",
     "type": "timeseries",
     "gridPos": { "h": 24, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(substrate_rpc_calls_finished{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc_calls_started",
     "type": "timeseries",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(substrate_rpc_calls_started{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc_calls_time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(substrate_rpc_calls_time_sum{instance=\"$instance\",job=\"$job\"}[5m]) / rate(substrate_rpc_calls_time_count{instance=\"$instance\",job=\"$job\"}[5m])",
       "legendFormat": "{{ method }} - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "ready_transactions_number",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "substrate_ready_transactions_number{instance=\"$instance\",job=\"$job\"}",
       "legendFormat": "ready_transactions_number"
      }
     ]
    },
    {
     "title": "rpc_requests_finished",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(substrate_rpc_requests_finished{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "rpc_requests_finished - [ {{ protocol }} ]"
      },
      {
       "expr": "rate(substrate_rpc_requests_started{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "rpc_requests_started - [ {{ protocol }} ]"
      }
     ]
    },
    {
     "title": "rpc session status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(substrate_rpc_sessions_closed{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Session Closed"
      },
      {
       "expr": "rate(substrate_rpc_sessions_opened[$__rate_interval])",
       "legendFormat": "Session Open:"
      }
     ]
    }
   ]
  },
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "connections_closed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_connections_closed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "connections_open",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_connections_opened_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "incoming_connections_handshake_errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_incoming_connections_handshake_errors_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "libp2p_distinct_peers_connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_distinct_peers_connections_closed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Close:"
    },
    {
     "expr": "rate(substrate_sub_libp2p_distinct_peers_connections_opened_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Open:"
    }
   ]
  },
  {
   "title": "libp2p_incoming_connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_incoming_connections_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Incoming P2P connections rate:"
    }
   ]
  },
  {
   "title": "libp2p_is_major_syncing",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_is_major_syncing{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "libp2p_is_major_syncing"
    }
   ]
  },
  {
   "title": "kademlia_random_queries [ 15m ]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_kademlia_random_queries_total{instance=\"$instance\",job=\"$job\"}[15m])",
     "legendFormat": "kademlia_random_queries"
    }
   ]
  },
  {
   "title": "kademlia_records_count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_kademlia_records_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "kademlia_records_count"
    }
   ]
  },
  {
   "title": "kademlia_records_sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_kademlia_records_sizes_total{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "kademlia_records_sizes"
    }
   ]
  },
  {
   "title": "libp2p_kbuckets_num_nodes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_kbuckets_num_nodes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "lower_ilog2_bucket_bound - [ {{ lower_ilog2_bucket_bound }} ]"
    }
   ]
  },
  {
   "title": "libp2p_notifications_streams",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_notifications_streams_closed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Closed - {{ protocol }}"
    },
    {
     "expr": "rate(substrate_sub_libp2p_notifications_streams_opened_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Opened - {{ protocol }}"
    }
   ]
  },
  {
   "title": "libp2p_notifications_sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_notifications_sizes_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) / rate(substrate_sub_libp2p_notifications_sizes_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ direction }} - {{ protocol }}"
    }
   ]
  },
  {
   "title": "libp2p_listeners_errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_listeners_errors_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "libp2p_listeners_errors"
    }
   ]
  },
  {
   "title": "libp2p_listeners_local_addresses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_listeners_local_addresses{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "libp2p_listeners_local_addresses"
    }
   ]
  },
  {
   "title": "libp2p_out_events_events rate",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_out_events_events_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ event_name }} - {{ name }}"
    }
   ]
  },
  {
   "title": "libp2p_out_events_notifications_sizes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_out_events_notifications_sizes{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ event_name }} - {{ name }}"
    }
   ]
  },
  {
   "title": "libp2p_out_events_num_channels",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_out_events_num_channels{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ event_name }} - {{ name }}"
    }
   ]
  },
  {
   "title": "libp2p_pending_connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_pending_connections{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "libp2p_pending_connections"
    }
   ]
  },
  {
   "title": "Peers count:",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Peers count:"
    }
   ]
  },
  {
   "title": "libp2p_requests_out_failure",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_requests_out_failure_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ protocol }} - {{ reason }}"
    }
   ]
  },
  {
   "title": "peerset_num_discovered",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "peerset_num_discovered"
    }
   ]
  },
  {
   "title": "pending_connections_errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_pending_connections_errors_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "TX Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 260 } },
  {
   "title": "txpool_block_transactions_pruned [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 261 },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_block_transactions_pruned{instance=\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "Time:"
    }
   ]
  },
  {
   "title": "libp2p_requests_out_success",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_requests_out_success_total_sum{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) / rate(substrate_sub_libp2p_requests_out_success_total_count{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "transactions_resubmitted",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_block_transactions_resubmitted{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "transactions_resubmitted"
    }
   ]
  },
  {
   "title": "txpool_block_transactions_pruned",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 282 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_block_transactions_pruned{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "txpool_block_transactions_pruned"
    }
   ]
  },
  {
   "title": "txpool_validations_finished",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 282 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_finished{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "txpool_validations_finished"
    }
   ]
  },
  {
   "title": "txpool_validations_invalid",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 295 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_invalid{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "txpool_validations_invalid"
    }
   ]
  },
  {
   "title": "txpool_validations_scheduled / txpool_submitted_transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 307 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_scheduled{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "txpool_validations_scheduled"
    },
    {
     "expr": "rate(substrate_sub_txpool_submitted_transactions[$__rate_interval])",
     "legendFormat": "txpool_submitted_transactions"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 317 } },
  {
   "title": "state_cache_bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 318 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "state_cache_bytes:"
    }
   ]
  },
  {
   "title": "storage_notification_subscribers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 318 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(substrate_storage_notification_subscribers{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ action }}:"
    }
   ]
  }
 ]
}